### ISSUE TITLE
加速完善

### ISSUE THREAD

**Issue by luxiaoming** [BCsl/WaterMonitor#1]
加速完善，加油

**Comment by BCsl** [comment]
这个项目没啥实际意义的，不需要star。只是用来实现自己个人的生活小需求。哈哈 @luxiaoming

**Comment by luxiaoming** [comment]
呵呵，看了下，以为你要补充呢。

**Comment by BCsl** [comment]
对啊，还要补充，只是一个目标手机在收到特定的电话拨入的时候，打开QQ特定联系人接通视频聊天的应用，目的是用来监视下家里的狗子

**Comment by luxiaoming** [comment]
想法不错啊，呵呵。赶紧写
