### ISSUE TITLE
缺少Privacy工具类

### ISSUE THREAD

**Issue by yangxiaoge** [BCsl/WaterMonitor#2]
github.hellocsl.smartmonitor.utils.Privacy

**Comment by BCsl** [comment]
import github.hellocsl.smartmonitor.utils.Privacy;这个没类只是再记录了默认的QQ帐号的常量，所以没上传，可以自己新建一个

**Comment by qq634421026** [comment]
apply plugin: 'android-apt' 
 apt 'com.jakewharton:butterknife-compiler:8.4.0'
这个两个是什么 没找到

**Comment by BCsl** [comment]
https://github.com/JakeWharton/butterknife @qq634421026
