### ISSUE TITLE
最后打开qq界面那个操作有问题

### ISSUE THREAD

**Issue by gudujiucheng** [BCsl/WaterMonitor#3]
在已经互相为好友的情况下，我打开的qq会话界面是没有“加号”按钮的，居然显示的是陌生人添加好友界面，是不是还需要一些参数。求解？？？

**Comment by BCsl** [comment]
@gudujiucheng  并不需要，你确定是互相好友了？另外确定好QQ号码是否正确

**Comment by gudujiucheng** [comment]
是的 互为好友了   魅蓝2    晚些我在换个qq换个机型  然后再来提问 感谢回答

**Comment by BCsl** [comment]
这个不应该哦   你试试直接在QQ打开那个联系人会不会是陌生人面板，不认为会和手机型号有关

**Comment by gudujiucheng** [comment]
![image](https://cloud.githubusercontent.com/assets/12092818/19851100/2bc64176-9f97-11e6-8424-81c6f4d2fde9.png)
就像这样一样，已经试验多个好友，明天再试试，可能我代码哪里看错了。明天在屡屡

**Comment by BCsl** [comment]
在QQ联系人那里打开也是这样？会不会你的QQ号码前后有空格？

**Comment by y6821552** [comment]
我这边也遇到这个问题了，机型是魅蓝note2，qq会话界面是没有“加号”按钮的，显示的是陌生人聊天记录页面。求帮助！3Q

**Comment by y6821552** [comment]
github.hellocsl.smartmonitor.utils.Privacy;类中设置的是server端qq号码还是client端的？应该是client端的QQ号把？

**Comment by y6821552** [comment]
我调试了下，感觉应该是这个问题：可以参考下

IdleState.java中：
![qq 20161104171959](https://cloud.githubusercontent.com/assets/17564659/20000614/5cf227be-a2b3-11e6-899a-a68986e3fb07.jpg)

**Comment by gudujiucheng** [comment]
@y6821552  感谢分享，这两天加班中，暂时没玩这个。

**Comment by BCsl** [comment]
@y6821552  那段代码是尝试从联系人名字得到要视频聊天的QQ号码，这样就可以动态的配置QQ号码，因为可以有多个Client，不需要改动代码，Privacy记录的是默认的QQ号码，所以Client端的备注要改成“WaterMonitor:QQ号码”这样的格式

**Comment by y6821552** [comment]
@BCsl 嗯，说的对。我现在还有个需求，我的手机前置摄像头坏了。能不能再加个操作，使用后置摄像头进行视频呢？

**Comment by BCsl** [comment]
可以啊，但我最近不打算做这个功能，因为还有其他事情要做，你完全可以自己来扩展的，理论上应该很容易，只需要增加个状态

**Comment by y6821552** [comment]
@BCsl 我用uiautomatorviewer没有找到转到后摄像头的控件的ID和名称，不知道该如何操作。我做了模拟点击，倒是可以使用后摄像头了。不知道大家有没有好的解决方案

**Comment by BCsl** [comment]
控件通过代码动态添加的话可能就没ID了，尝试从ViewGroup中更加Index找到这个View也可以，但是界面如果升级更新之后就可能变了，如果真的找不到就只能模拟点击了

**Comment by y6821552** [comment]
@BCsl uiautomatorviewer这个没找到ID，所以我就直接模拟点击了。感谢！
